#!/bin/bash

set -eo pipefail

while [[ "$#" -gt 0 ]]; do
	case $1 in
		-i) output=inplace ;;
		-p|--patch) output=patch ;;
		-s|--syntax) postprocess="cat" ;;
		*) break ;;
	esac
	shift
done

_=${1?missing path}

file=${*: -1}

# TODO: validate input strictly
# TODO: improve error messages
# TODO: accept multiple files
# TODO: accept directory for recursive *.swift walk
# TODO: walk CWD for no args
# TODO: accept stdin
# TODO: accept *.pbxproj:target

run() {
	swift -frontend -emit-syntax "$file" |
		jq "${@:1:$#-1}" |
		${postprocess-"$(dirname "$0")"/absorb-syntax.jq}
}

case $output in
	inplace)
		tmp=$(mktemp)
		run "${@}" >"$tmp"
		mv "$tmp" "$file"
		;;
	patch)
		tmp=$(mktemp)
		run "${@}" >"$tmp"
		diff -u "$file" "$tmp"
		;;
	*)
		run "${@}"
		;;
esac
