#!/bin/bash

set -eo pipefail

while [[ "$#" -gt 0 ]]; do
	case $1 in
		-i) output=inplace ;;
		*) break ;;
	esac
	shift
done

_=${1?missing path}

file=${*: -1}

# TODO: validate input strictly
# TODO: improve error messages
# TODO: --diff mode
# TODO: --patch mode (interactive)
# TODO: --syntax output AST
# TODO: accept multiple files
# TODO: accept directory for recursive *.swift walk
# TODO: walk CWD for no args
# TODO: accept stdin
# TODO: accept *.pbxproj:target

run() {
	swift -frontend -emit-syntax "$file" |
		jq "${@:1:$#-1}" |
		"$(dirname "$0")"/absorb-syntax.jq
}

case $output in
	inplace)
		tmp=$(mktemp)
		run "${@}" >"$tmp"
		mv "$tmp" "$file"
		;;
	*)
		run "${@}"
		;;
esac
